<!DOCTYPE html>
<html>
<body>

<?php

$jsonobj = '{
    "tournament": {
        "id": 15193348,
        "name": "\"Knock Out Burgame\" - Burgame Ironfist Tournament 2",
        "url": "q4jzyjml",
        "description": "Torneo de Tekken 8 de",
        "tournament_type": "double elimination",
        "started_at": "2024-10-20T15:04:09.554-06:00",
        "completed_at": "2024-10-20T19:41:30.887-06:00",
        "require_score_agreement": false,
        "notify_users_when_matches_open": true,
        "created_at": "2024-10-02T12:11:32.341-06:00",
        "updated_at": "2024-10-20T19:41:31.267-06:00",
        "state": "complete",
        "open_signup": true,
        "notify_users_when_the_tournament_ends": true,
        "progress_meter": 100,
        "quick_advance": false,
        "hold_third_place_match": false,
        "pts_for_game_win": "0.0",
        "pts_for_game_tie": "0.0",
        "pts_for_match_win": "1.0",
        "pts_for_match_tie": "0.5",
        "pts_for_bye": "1.0",
        "swiss_rounds": 5,
        "private": false,
        "ranked_by": "match wins",
        "show_rounds": true,
        "hide_forum": false,
        "sequential_pairings": false,
        "accept_attachments": false,
        "rr_pts_for_game_win": "0.0",
        "rr_pts_for_game_tie": "0.0",
        "rr_pts_for_match_win": "1.0",
        "rr_pts_for_match_tie": "0.5",
        "created_by_api": false,
        "credit_capped": false,
        "category": null,
        "hide_seeds": false,
        "prediction_method": 0,
        "predictions_opened_at": null,
        "anonymous_voting": false,
        "max_predictions_per_user": 1,
        "signup_cap": null,
        "game_id": 236261,
        "participants_count": 17,
        "group_stages_enabled": false,
        "allow_participant_match_reporting": true,
        "teams": false,
        "check_in_duration": null,
        "start_at": "2024-10-20T15:00:00.000-06:00",
        "started_checking_in_at": null,
        "tie_breaks": [
            "match wins vs tied",
            "game wins",
            "points scored"
        ],
        "locked_at": null,
        "event_id": null,
        "public_predictions_before_start_time": false,
        "ranked": null,
        "grand_finals_modifier": null,
        "predict_the_losers_bracket": false,
        "spam": null,
        "ham": null,
        "rr_iterations": null,
        "tournament_registration_id": null,
        "donation_contest_enabled": null,
        "mandatory_donation": null,
        "non_elimination_tournament_data": {
            "participants_per_match": ""
        },
        "auto_assign_stations": null,
        "only_start_matches_with_stations": null,
        "registration_fee": "0.0",
        "registration_type": "free",
        "split_participants": false,
        "allowed_regions": [],
        "show_participant_country": null,
        "program_id": null,
        "program_classification_ids_allowed": null,
        "team_size_range": null,
        "toxic": null,
        "use_new_style": null,
        "optional_display_data": {
            "show_standings": "1",
            "show_announcements": true
        },
        "processing": false,
        "oauth_application_id": null,
        "hide_bracket_preview": false,
        "consolation_matches_target_rank": null,
        "review_swiss_pairings_before_starting_rounds": null,
        "allow_incomplete_rosters": null,
        "participants": [
            {
                "participant": {
                    "id": 243599565,
                    "tournament_id": 15193348,
                    "name": "TWPYShaka",
                    "seed": 1,
                    "active": true,
                    "created_at": "2024-10-08T13:41:42.379-06:00",
                    "updated_at": "2024-10-08T14:16:41.555-06:00",
                    "invite_email": null,
                    "final_rank": 9,
                    "misc": null,
                    "icon": null,
                    "on_waiting_list": false,
                    "invitation_id": null,
                    "group_id": null,
                    "checked_in_at": null,
                    "ranked_member_id": null,
                    "custom_field_response": null,
                    "clinch": null,
                    "integration_uids": null,
                    "challonge_username": "TWPYShaka",
                    "challonge_user_id": 2104225,
                    "challonge_email_address_verified": true,
                    "removable": false,
                    "participatable_or_invitation_attached": true,
                    "confirm_remove": true,
                    "invitation_pending": false,
                    "display_name_with_invitation_email_address": "TWPYShaka",
                    "email_hash": "d3fd189785e9464b00b1e3235c883c45",
                    "username": "TWPYShaka",
                    "display_name": "TWPYShaka",
                    "attached_participatable_portrait_url": "https://s3.amazonaws.com/challonge_app/users/images/002/104/225/xlarge/Snapchat-2118125963.png",
                    "can_check_in": false,
                    "checked_in": false,
                    "reactivatable": false,
                    "check_in_open": false,
                    "group_player_ids": [],
                    "has_irrelevant_seed": false,
                    "ordinal_seed": "1st",
                    "roster_complete": null,
                    "roster_size": null
                }
            },
            {
                "participant": {
                    "id": 244664837,
                    "tournament_id": 15193348,
                    "name": "TrunksEsp",
                    "seed": 2,
                    "active": true,
                    "created_at": "2024-10-20T14:55:05.912-06:00",
                    "updated_at": "2024-10-20T14:55:05.912-06:00",
                    "invite_email": null,
                    "final_rank": 13,
                    "misc": null,
                    "icon": null,
                    "on_waiting_list": false,
                    "invitation_id": null,
                    "group_id": null,
                    "checked_in_at": null,
                    "ranked_member_id": null,
                    "custom_field_response": null,
                    "clinch": null,
                    "integration_uids": null,
                    "challonge_username": "TrunksEsp",
                    "challonge_user_id": 5063639,
                    "challonge_email_address_verified": false,
                    "removable": false,
                    "participatable_or_invitation_attached": true,
                    "confirm_remove": true,
                    "invitation_pending": false,
                    "display_name_with_invitation_email_address": "TrunksEsp",
                    "email_hash": "43e17f04b588ce1e7489f8a65b143019",
                    "username": "TrunksEsp",
                    "display_name": "TrunksEsp",
                    "attached_participatable_portrait_url": "https://secure.gravatar.com/avatar/4a856f0e25af41f4090500095ef3c736?r=r&s=96&d=https://s3.amazonaws.com/challonge_app/misc/challonge_fireball_gray.png",
                    "can_check_in": false,
                    "checked_in": false,
                    "reactivatable": false,
                    "check_in_open": false,
                    "group_player_ids": [],
                    "has_irrelevant_seed": false,
                    "ordinal_seed": "2nd",
                    "roster_complete": null,
                    "roster_size": null
                }
            },
            {
                "participant": {
                    "id": 244656335,
                    "tournament_id": 15193348,
                    "name": "ssnakepy",
                    "seed": 3,
                    "active": true,
                    "created_at": "2024-10-20T13:15:17.593-06:00",
                    "updated_at": "2024-10-20T13:15:17.593-06:00",
                    "invite_email": null,
                    "final_rank": 1,
                    "misc": null,
                    "icon": null,
                    "on_waiting_list": false,
                    "invitation_id": null,
                    "group_id": null,
                    "checked_in_at": null,
                    "ranked_member_id": null,
                    "custom_field_response": null,
                    "clinch": null,
                    "integration_uids": null,
                    "challonge_username": "ssnakepy",
                    "challonge_user_id": 7097104,
                    "challonge_email_address_verified": true,
                    "removable": false,
                    "participatable_or_invitation_attached": true,
                    "confirm_remove": true,
                    "invitation_pending": false,
                    "display_name_with_invitation_email_address": "ssnakepy",
                    "email_hash": "c088ea8c26529ded05f834a0b16bf41e",
                    "username": "ssnakepy",
                    "display_name": "ssnakepy",
                    "attached_participatable_portrait_url": "https://secure.gravatar.com/avatar/c088ea8c26529ded05f834a0b16bf41e?r=r&s=96&d=https://s3.amazonaws.com/challonge_app/misc/challonge_fireball_gray.png",
                    "can_check_in": false,
                    "checked_in": false,
                    "reactivatable": false,
                    "check_in_open": false,
                    "group_player_ids": [],
                    "has_irrelevant_seed": false,
                    "ordinal_seed": "3rd",
                    "roster_complete": null,
                    "roster_size": null
                }
            },
            {
                "participant": {
                    "id": 244654296,
                    "tournament_id": 15193348,
                    "name": "Yired",
                    "seed": 4,
                    "active": true,
                    "created_at": "2024-10-20T12:51:14.176-06:00",
                    "updated_at": "2024-10-20T12:51:14.176-06:00",
                    "invite_email": null,
                    "final_rank": 13,
                    "misc": null,
                    "icon": null,
                    "on_waiting_list": false,
                    "invitation_id": null,
                    "group_id": null,
                    "checked_in_at": null,
                    "ranked_member_id": null,
                    "custom_field_response": null,
                    "clinch": null,
                    "integration_uids": null,
                    "challonge_username": "Yired",
                    "challonge_user_id": 1779975,
                    "challonge_email_address_verified": true,
                    "removable": false,
                    "participatable_or_invitation_attached": true,
                    "confirm_remove": true,
                    "invitation_pending": false,
                    "display_name_with_invitation_email_address": "Yired",
                    "email_hash": "6d97567f7d870c740ee875cad65a3e6a",
                    "username": "Yired",
                    "display_name": "Yired",
                    "attached_participatable_portrait_url": "https://s3.amazonaws.com/challonge_app/users/images/001/779/975/xlarge/FFVII_Remake_Profile_Picture.png",
                    "can_check_in": false,
                    "checked_in": false,
                    "reactivatable": false,
                    "check_in_open": false,
                    "group_player_ids": [],
                    "has_irrelevant_seed": false,
                    "ordinal_seed": "4th",
                    "roster_complete": null,
                    "roster_size": null
                }
            },
            {
                "participant": {
                    "id": 243600692,
                    "tournament_id": 15193348,
                    "name": "LMDTLightGear",
                    "seed": 5,
                    "active": true,
                    "created_at": "2024-10-08T14:00:58.920-06:00",
                    "updated_at": "2024-10-08T14:00:58.920-06:00",
                    "invite_email": null,
                    "final_rank": 9,
                    "misc": null,
                    "icon": null,
                    "on_waiting_list": false,
                    "invitation_id": null,
                    "group_id": null,
                    "checked_in_at": null,
                    "ranked_member_id": null,
                    "custom_field_response": null,
                    "clinch": null,
                    "integration_uids": null,
                    "challonge_username": "LMDTLightGear",
                    "challonge_user_id": 3145329,
                    "challonge_email_address_verified": true,
                    "removable": false,
                    "participatable_or_invitation_attached": true,
                    "confirm_remove": true,
                    "invitation_pending": false,
                    "display_name_with_invitation_email_address": "LMDTLightGear",
                    "email_hash": "d3169fa425fe0ca32d40a7ebd5e1b46a",
                    "username": "LMDTLightGear",
                    "display_name": "LMDTLightGear",
                    "attached_participatable_portrait_url": "https://s3.amazonaws.com/challonge_app/users/images/003/145/329/xlarge/Travis_Touchdown.png",
                    "can_check_in": false,
                    "checked_in": false,
                    "reactivatable": false,
                    "check_in_open": false,
                    "group_player_ids": [],
                    "has_irrelevant_seed": false,
                    "ordinal_seed": "5th",
                    "roster_complete": null,
                    "roster_size": null
                }
            },
            {
                "participant": {
                    "id": 244464915,
                    "tournament_id": 15193348,
                    "name": "WARIOTWPY",
                    "seed": 6,
                    "active": true,
                    "created_at": "2024-10-18T15:50:13.356-06:00",
                    "updated_at": "2024-10-18T15:50:13.356-06:00",
                    "invite_email": null,
                    "final_rank": 9,
                    "misc": null,
                    "icon": null,
                    "on_waiting_list": false,
                    "invitation_id": null,
                    "group_id": null,
                    "checked_in_at": null,
                    "ranked_member_id": null,
                    "custom_field_response": null,
                    "clinch": null,
                    "integration_uids": null,
                    "challonge_username": "WARIOTWPY",
                    "challonge_user_id": 5665627,
                    "challonge_email_address_verified": true,
                    "removable": false,
                    "participatable_or_invitation_attached": true,
                    "confirm_remove": true,
                    "invitation_pending": false,
                    "display_name_with_invitation_email_address": "WARIOTWPY",
                    "email_hash": "49ccb92e220293d6d39d9eab12bf8e78",
                    "username": "WARIOTWPY",
                    "display_name": "WARIOTWPY",
                    "attached_participatable_portrait_url": "https://secure.gravatar.com/avatar/49ccb92e220293d6d39d9eab12bf8e78?r=r&s=96&d=https://s3.amazonaws.com/challonge_app/misc/challonge_fireball_gray.png",
                    "can_check_in": false,
                    "checked_in": false,
                    "reactivatable": false,
                    "check_in_open": false,
                    "group_player_ids": [],
                    "has_irrelevant_seed": false,
                    "ordinal_seed": "6th",
                    "roster_complete": null,
                    "roster_size": null
                }
            },
            {
                "participant": {
                    "id": 243111509,
                    "tournament_id": 15193348,
                    "name": "SaikeNN",
                    "seed": 7,
                    "active": true,
                    "created_at": "2024-10-02T12:13:55.297-06:00",
                    "updated_at": "2024-10-02T12:13:55.297-06:00",
                    "invite_email": null,
                    "final_rank": 5,
                    "misc": null,
                    "icon": null,
                    "on_waiting_list": false,
                    "invitation_id": null,
                    "group_id": null,
                    "checked_in_at": null,
                    "ranked_member_id": null,
                    "custom_field_response": null,
                    "clinch": null,
                    "integration_uids": null,
                    "challonge_username": "SaikeNN",
                    "challonge_user_id": 4568795,
                    "challonge_email_address_verified": true,
                    "removable": false,
                    "participatable_or_invitation_attached": true,
                    "confirm_remove": true,
                    "invitation_pending": false,
                    "display_name_with_invitation_email_address": "SaikeNN",
                    "email_hash": "48ccfcdaf1e86537ba0c3690c73d38f8",
                    "username": "SaikeNN",
                    "display_name": "SaikeNN",
                    "attached_participatable_portrait_url": "https://secure.gravatar.com/avatar/48ccfcdaf1e86537ba0c3690c73d38f8?r=r&s=96&d=https://s3.amazonaws.com/challonge_app/misc/challonge_fireball_gray.png",
                    "can_check_in": false,
                    "checked_in": false,
                    "reactivatable": false,
                    "check_in_open": false,
                    "group_player_ids": [],
                    "has_irrelevant_seed": false,
                    "ordinal_seed": "7th",
                    "roster_complete": null,
                    "roster_size": null
                }
            },
            {
                "participant": {
                    "id": 244664852,
                    "tournament_id": 15193348,
                    "name": "Lagan",
                    "seed": 8,
                    "active": true,
                    "created_at": "2024-10-20T14:55:35.886-06:00",
                    "updated_at": "2024-10-20T14:55:35.886-06:00",
                    "invite_email": null,
                    "final_rank": 13,
                    "misc": null,
                    "icon": null,
                    "on_waiting_list": false,
                    "invitation_id": null,
                    "group_id": null,
                    "checked_in_at": null,
                    "ranked_member_id": null,
                    "custom_field_response": null,
                    "clinch": null,
                    "integration_uids": null,
                    "challonge_username": null,
                    "challonge_user_id": null,
                    "challonge_email_address_verified": null,
                    "removable": false,
                    "participatable_or_invitation_attached": false,
                    "confirm_remove": true,
                    "invitation_pending": false,
                    "display_name_with_invitation_email_address": "Lagan",
                    "email_hash": null,
                    "username": null,
                    "display_name": "Lagan",
                    "attached_participatable_portrait_url": null,
                    "can_check_in": false,
                    "checked_in": false,
                    "reactivatable": false,
                    "check_in_open": false,
                    "group_player_ids": [],
                    "has_irrelevant_seed": false,
                    "ordinal_seed": "8th",
                    "roster_complete": null,
                    "roster_size": null
                }
            },
            {
                "participant": {
                    "id": 243599262,
                    "tournament_id": 15193348,
                    "name": "BG_Hosco",
                    "seed": 9,
                    "active": true,
                    "created_at": "2024-10-08T13:35:02.952-06:00",
                    "updated_at": "2024-10-08T13:35:02.952-06:00",
                    "invite_email": null,
                    "final_rank": 3,
                    "misc": null,
                    "icon": null,
                    "on_waiting_list": false,
                    "invitation_id": null,
                    "group_id": null,
                    "checked_in_at": null,
                    "ranked_member_id": null,
                    "custom_field_response": null,
                    "clinch": null,
                    "integration_uids": null,
                    "challonge_username": "BG_Hosco",
                    "challonge_user_id": 5044515,
                    "challonge_email_address_verified": true,
                    "removable": false,
                    "participatable_or_invitation_attached": true,
                    "confirm_remove": true,
                    "invitation_pending": false,
                    "display_name_with_invitation_email_address": "BG_Hosco",
                    "email_hash": "15c4514caa4e3600416df9ab8919f6ee",
                    "username": "BG_Hosco",
                    "display_name": "BG_Hosco",
                    "attached_participatable_portrait_url": "https://secure.gravatar.com/avatar/15c4514caa4e3600416df9ab8919f6ee?r=r&s=96&d=https://s3.amazonaws.com/challonge_app/misc/challonge_fireball_gray.png",
                    "can_check_in": false,
                    "checked_in": false,
                    "reactivatable": false,
                    "check_in_open": false,
                    "group_player_ids": [],
                    "has_irrelevant_seed": false,
                    "ordinal_seed": "9th",
                    "roster_complete": null,
                    "roster_size": null
                }
            },
            {
                "participant": {
                    "id": 244664827,
                    "tournament_id": 15193348,
                    "name": "Joaqwer",
                    "seed": 10,
                    "active": true,
                    "created_at": "2024-10-20T14:54:14.677-06:00",
                    "updated_at": "2024-10-20T14:54:14.677-06:00",
                    "invite_email": null,
                    "final_rank": 9,
                    "misc": null,
                    "icon": null,
                    "on_waiting_list": false,
                    "invitation_id": null,
                    "group_id": null,
                    "checked_in_at": null,
                    "ranked_member_id": null,
                    "custom_field_response": null,
                    "clinch": null,
                    "integration_uids": null,
                    "challonge_username": null,
                    "challonge_user_id": null,
                    "challonge_email_address_verified": null,
                    "removable": false,
                    "participatable_or_invitation_attached": false,
                    "confirm_remove": true,
                    "invitation_pending": false,
                    "display_name_with_invitation_email_address": "Joaqwer",
                    "email_hash": null,
                    "username": null,
                    "display_name": "Joaqwer",
                    "attached_participatable_portrait_url": null,
                    "can_check_in": false,
                    "checked_in": false,
                    "reactivatable": false,
                    "check_in_open": false,
                    "group_player_ids": [],
                    "has_irrelevant_seed": false,
                    "ordinal_seed": "10th",
                    "roster_complete": null,
                    "roster_size": null
                }
            },
            {
                "participant": {
                    "id": 244664779,
                    "tournament_id": 15193348,
                    "name": "Yuya",
                    "seed": 11,
                    "active": true,
                    "created_at": "2024-10-20T14:52:36.238-06:00",
                    "updated_at": "2024-10-20T14:52:36.238-06:00",
                    "invite_email": null,
                    "final_rank": 17,
                    "misc": null,
                    "icon": null,
                    "on_waiting_list": false,
                    "invitation_id": null,
                    "group_id": null,
                    "checked_in_at": null,
                    "ranked_member_id": null,
                    "custom_field_response": null,
                    "clinch": null,
                    "integration_uids": null,
                    "challonge_username": null,
                    "challonge_user_id": null,
                    "challonge_email_address_verified": null,
                    "removable": false,
                    "participatable_or_invitation_attached": false,
                    "confirm_remove": true,
                    "invitation_pending": false,
                    "display_name_with_invitation_email_address": "Yuya",
                    "email_hash": null,
                    "username": null,
                    "display_name": "Yuya",
                    "attached_participatable_portrait_url": null,
                    "can_check_in": false,
                    "checked_in": false,
                    "reactivatable": false,
                    "check_in_open": false,
                    "group_player_ids": [],
                    "has_irrelevant_seed": false,
                    "ordinal_seed": "11th",
                    "roster_complete": null,
                    "roster_size": null
                }
            },
            {
                "participant": {
                    "id": 243600164,
                    "tournament_id": 15193348,
                    "name": "DamianCp",
                    "seed": 12,
                    "active": true,
                    "created_at": "2024-10-08T13:50:30.235-06:00",
                    "updated_at": "2024-10-20T14:54:07.664-06:00",
                    "invite_email": null,
                    "final_rank": 5,
                    "misc": null,
                    "icon": null,
                    "on_waiting_list": false,
                    "invitation_id": null,
                    "group_id": null,
                    "checked_in_at": null,
                    "ranked_member_id": null,
                    "custom_field_response": null,
                    "clinch": null,
                    "integration_uids": null,
                    "challonge_username": "DamianCp",
                    "challonge_user_id": 5472219,
                    "challonge_email_address_verified": true,
                    "removable": false,
                    "participatable_or_invitation_attached": true,
                    "confirm_remove": true,
                    "invitation_pending": false,
                    "display_name_with_invitation_email_address": "DamianCp",
                    "email_hash": "fd4f61632a462067c6f4e14fe39dee07",
                    "username": "DamianCp",
                    "display_name": "DamianCp",
                    "attached_participatable_portrait_url": "https://secure.gravatar.com/avatar/fd4f61632a462067c6f4e14fe39dee07?r=r&s=96&d=https://s3.amazonaws.com/challonge_app/misc/challonge_fireball_gray.png",
                    "can_check_in": false,
                    "checked_in": false,
                    "reactivatable": false,
                    "check_in_open": false,
                    "group_player_ids": [],
                    "has_irrelevant_seed": false,
                    "ordinal_seed": "12th",
                    "roster_complete": null,
                    "roster_size": null
                }
            },
            {
                "participant": {
                    "id": 243600127,
                    "tournament_id": 15193348,
                    "name": "DannyDacak",
                    "seed": 13,
                    "active": true,
                    "created_at": "2024-10-08T13:48:26.232-06:00",
                    "updated_at": "2024-10-20T14:54:38.825-06:00",
                    "invite_email": null,
                    "final_rank": 4,
                    "misc": null,
                    "icon": null,
                    "on_waiting_list": false,
                    "invitation_id": null,
                    "group_id": null,
                    "checked_in_at": null,
                    "ranked_member_id": null,
                    "custom_field_response": null,
                    "clinch": null,
                    "integration_uids": null,
                    "challonge_username": "Danns_",
                    "challonge_user_id": 5042005,
                    "challonge_email_address_verified": true,
                    "removable": false,
                    "participatable_or_invitation_attached": true,
                    "confirm_remove": true,
                    "invitation_pending": false,
                    "display_name_with_invitation_email_address": "DannyDacak",
                    "email_hash": "52c823f695a3b1cf975fee922b9fda52",
                    "username": "Danns_",
                    "display_name": "DannyDacak",
                    "attached_participatable_portrait_url": "https://secure.gravatar.com/avatar/52c823f695a3b1cf975fee922b9fda52?r=r&s=96&d=https://s3.amazonaws.com/challonge_app/misc/challonge_fireball_gray.png",
                    "can_check_in": false,
                    "checked_in": false,
                    "reactivatable": false,
                    "check_in_open": false,
                    "group_player_ids": [],
                    "has_irrelevant_seed": false,
                    "ordinal_seed": "13th",
                    "roster_complete": null,
                    "roster_size": null
                }
            },
            {
                "participant": {
                    "id": 243112026,
                    "tournament_id": 15193348,
                    "name": "Focus_Pocus_",
                    "seed": 14,
                    "active": true,
                    "created_at": "2024-10-02T12:21:07.447-06:00",
                    "updated_at": "2024-10-02T12:21:07.447-06:00",
                    "invite_email": null,
                    "final_rank": 13,
                    "misc": null,
                    "icon": null,
                    "on_waiting_list": false,
                    "invitation_id": null,
                    "group_id": null,
                    "checked_in_at": null,
                    "ranked_member_id": null,
                    "custom_field_response": null,
                    "clinch": null,
                    "integration_uids": null,
                    "challonge_username": "Focus_Pocus_",
                    "challonge_user_id": 6701078,
                    "challonge_email_address_verified": true,
                    "removable": false,
                    "participatable_or_invitation_attached": true,
                    "confirm_remove": true,
                    "invitation_pending": false,
                    "display_name_with_invitation_email_address": "Focus_Pocus_",
                    "email_hash": "acbc79995e0d0cd0264fbb19e88050f4",
                    "username": "Focus_Pocus_",
                    "display_name": "Focus_Pocus_",
                    "attached_participatable_portrait_url": "https://secure.gravatar.com/avatar/acbc79995e0d0cd0264fbb19e88050f4?r=r&s=96&d=https://s3.amazonaws.com/challonge_app/misc/challonge_fireball_gray.png",
                    "can_check_in": false,
                    "checked_in": false,
                    "reactivatable": false,
                    "check_in_open": false,
                    "group_player_ids": [],
                    "has_irrelevant_seed": false,
                    "ordinal_seed": "14th",
                    "roster_complete": null,
                    "roster_size": null
                }
            },
            {
                "participant": {
                    "id": 243113109,
                    "tournament_id": 15193348,
                    "name": "SirBull1",
                    "seed": 15,
                    "active": true,
                    "created_at": "2024-10-02T12:41:04.339-06:00",
                    "updated_at": "2024-10-02T12:41:04.339-06:00",
                    "invite_email": null,
                    "final_rank": 7,
                    "misc": null,
                    "icon": null,
                    "on_waiting_list": false,
                    "invitation_id": null,
                    "group_id": null,
                    "checked_in_at": null,
                    "ranked_member_id": null,
                    "custom_field_response": null,
                    "clinch": null,
                    "integration_uids": null,
                    "challonge_username": "SirBull1",
                    "challonge_user_id": 7026481,
                    "challonge_email_address_verified": false,
                    "removable": false,
                    "participatable_or_invitation_attached": true,
                    "confirm_remove": true,
                    "invitation_pending": false,
                    "display_name_with_invitation_email_address": "SirBull1",
                    "email_hash": "0908dcd7f18eec208fff960093b14301",
                    "username": "SirBull1",
                    "display_name": "SirBull1",
                    "attached_participatable_portrait_url": "https://secure.gravatar.com/avatar/0908dcd7f18eec208fff960093b14301?r=r&s=96&d=https://s3.amazonaws.com/challonge_app/misc/challonge_fireball_gray.png",
                    "can_check_in": false,
                    "checked_in": false,
                    "reactivatable": false,
                    "check_in_open": false,
                    "group_player_ids": [],
                    "has_irrelevant_seed": false,
                    "ordinal_seed": "15th",
                    "roster_complete": null,
                    "roster_size": null
                }
            },
            {
                "participant": {
                    "id": 244656920,
                    "tournament_id": 15193348,
                    "name": "COLORADOGAMARRA",
                    "seed": 16,
                    "active": true,
                    "created_at": "2024-10-20T13:20:47.561-06:00",
                    "updated_at": "2024-10-20T13:20:47.561-06:00",
                    "invite_email": null,
                    "final_rank": 7,
                    "misc": null,
                    "icon": null,
                    "on_waiting_list": false,
                    "invitation_id": null,
                    "group_id": null,
                    "checked_in_at": null,
                    "ranked_member_id": null,
                    "custom_field_response": null,
                    "clinch": null,
                    "integration_uids": null,
                    "challonge_username": "COLORADOGAMARRA",
                    "challonge_user_id": 7097109,
                    "challonge_email_address_verified": false,
                    "removable": false,
                    "participatable_or_invitation_attached": true,
                    "confirm_remove": true,
                    "invitation_pending": false,
                    "display_name_with_invitation_email_address": "COLORADOGAMARRA",
                    "email_hash": "34f4496a1f5c275eaba8b5286d312b88",
                    "username": "COLORADOGAMARRA",
                    "display_name": "COLORADOGAMARRA",
                    "attached_participatable_portrait_url": "https://secure.gravatar.com/avatar/34f4496a1f5c275eaba8b5286d312b88?r=r&s=96&d=https://s3.amazonaws.com/challonge_app/misc/challonge_fireball_gray.png",
                    "can_check_in": false,
                    "checked_in": false,
                    "reactivatable": false,
                    "check_in_open": false,
                    "group_player_ids": [],
                    "has_irrelevant_seed": false,
                    "ordinal_seed": "16th",
                    "roster_complete": null,
                    "roster_size": null
                }
            },
            {
                "participant": {
                    "id": 243598551,
                    "tournament_id": 15193348,
                    "name": "RushadorCuidadoso",
                    "seed": 17,
                    "active": true,
                    "created_at": "2024-10-08T13:18:28.342-06:00",
                    "updated_at": "2024-10-08T13:18:28.342-06:00",
                    "invite_email": null,
                    "final_rank": 2,
                    "misc": null,
                    "icon": null,
                    "on_waiting_list": false,
                    "invitation_id": null,
                    "group_id": null,
                    "checked_in_at": null,
                    "ranked_member_id": null,
                    "custom_field_response": null,
                    "clinch": null,
                    "integration_uids": null,
                    "challonge_username": "RushadorCuidadoso",
                    "challonge_user_id": 4437119,
                    "challonge_email_address_verified": true,
                    "removable": false,
                    "participatable_or_invitation_attached": true,
                    "confirm_remove": true,
                    "invitation_pending": false,
                    "display_name_with_invitation_email_address": "RushadorCuidadoso",
                    "email_hash": "a5e0175d2d6e5216abc5139cd2148d2b",
                    "username": "RushadorCuidadoso",
                    "display_name": "RushadorCuidadoso",
                    "attached_participatable_portrait_url": "https://secure.gravatar.com/avatar/a5e0175d2d6e5216abc5139cd2148d2b?r=r&s=96&d=https://s3.amazonaws.com/challonge_app/misc/challonge_fireball_gray.png",
                    "can_check_in": false,
                    "checked_in": false,
                    "reactivatable": false,
                    "check_in_open": false,
                    "group_player_ids": [],
                    "has_irrelevant_seed": false,
                    "ordinal_seed": "17th",
                    "roster_complete": null,
                    "roster_size": null
                }
            }
        ],
        "description_source": "Torneo de Tekken 8 de",
        "subdomain": null,
        "full_challonge_url": "https://challonge.com/q4jzyjml",
        "live_image_url": "https://challonge.com/q4jzyjml.svg",
        "sign_up_url": "https://challonge.com/tournaments/signup/NhUeRE87KJ",
        "review_before_finalizing": true,
        "accepting_predictions": false,
        "participants_locked": true,
        "game_name": "TEKKEN 8",
        "participants_swappable": false,
        "team_convertable": false,
        "group_stages_were_started": false
    }
}';

//echo $jsonobj;
//var_dump(json_decode($jsonobj,true));
$datos = json_decode($jsonobj,true);
$participantes = $datos["tournament"]["participants"];
?>
<table border=1>
<tr><th>Torneo ID</th><th>Participante</th><th>Posicion final</th></tr>
<?php
foreach($participantes as $part){
    $parti="";
    if ($part["participant"]["challonge_username"]==null || $part["participant"]["challonge_username"]==""){
        $parti=$part["participant"]["name"];
    }else{
        $parti=$part["participant"]["challonge_username"];
    }
    echo "<tr><td>".$part["participant"]["tournament_id"]."</td><td>$parti</td><td>".$part["participant"]["final_rank"]."</td></tr>";
}
?>
</table>
</body>
</html>