import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

import Navbar from "@/components/navbar";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const warsaw = localFont({
  src: [
    {
      path: "../../public/fonts/WarsawGothic.otf",
      weight: "700",
    },
  ],
  variable: "--font-warsaw",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body

        className={`${geistSans.variable} ${geistMono.variable} ${warsaw.variable} antialiased font-warsaw text-5xl italic bg-gradient-to-br from-[#630D33] to-[#277687] h-screen`}
      >
        <Navbar />


        {children}
      </body>
    </html>
  );
}
